apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-aws-vpc
  description: Terraform module to create AWS VPC resources
spec:
  type: service # can be one of: service, library, website, iac-pipeline
  lifecycle: production # can be one of: experimental, production, deprecated
  owner: team-platform-enablement # your existing tech team in Backstage, i.e. team-developer-platforms